#!/bin/bash

# Generates the favicon from an input png

name=$1

sizes=(16 24 32 48 64)
files=()

for size in "${sizes[@]}"
do
    convert ${name}.png -resize ${size}x${size} ${name}-${size}.png
    files+=("${name}-${size}.png")
done

convert "${files[@]}" ${name}.ico
rm favicon-*.png
