#!/bin/bash

# Converts the image to PNG
# Example:
# shq-image bits-must-flow 4

# Scaling factor
if [ -z ${2+x} ]
then
    scale=1
else
    scale=$2
fi

name=$1
date=$(grep date ${name}.md | awk '{print $2}' | awk -F"-" '{print $1}')

svgexport ${name}.svg ${name}.png ${scale}x

# Copyright notice
convert ${name}.png -gravity southeast \
    -font DejaVu-Sans \
    -pointsize $(($scale * 20)) \
    -stroke '#FFFF' -strokewidth 2 -annotate +$(($scale * 10))+$(($scale * 10)) "©${date}" \
    -stroke  none   -fill white    -annotate +$(($scale * 10))+$(($scale * 10)) "©${date}" \
    ${name}_copyright.png