#!/bin/bash

# Converts the image to PNG and produces a watermarked form in the end
# Example:
# svg-export-wm bits-must-flow

name=$1

hq-image ${name}
composite -dissolve 25% -gravity center /watermark/watermark.png ${name}.png  wm-${name}.png
convert -sharpen 0x1.2 -resize 60% -quality 5 wm-${name}.png wm-${name}.png