#!/bin/bash

# Converts the image to PNG and produces a watermarked form in the end
# Example:
# watermark bits-must-flow

name=$1
scale=$2

hq-image ${name} ${scale}
composite -dissolve 35% -gravity center /watermark/watermark.png ${name}_copyright.png  wm-${name}.png
convert -sharpen 0x1.2 -resize 40% -quality 2 -resample 50 wm-${name}.png wm-${name}.png